### PR TITLE
use named arguments in all sub-commands thanks to cmdliner monadic syntax

### PR DESCRIPTION
**Pull request by zapashcanon**

### CODE REVIEW

**Comment by zapashcanon** [comment]
cc @filipeom, you may be interested by this in other projects :-)

**Comment by filipeom** [comment]
> cc @filipeom, you may be interested by this in other projects :-)

I was just looking at this, and after reviewing the code, I can't understand why it's better this way (other than the fact that it looks more declarative and satisfying :relaxed:).  

Could you briefly explain if there are any functional improvements to using the monadic syntax?

I'm going to do this on smtml :sweat_smile:

**Comment by zapashcanon** [comment]
It allows named arguments, so you don't have to worry about the order anymore, which is nice when you have a lot of them! :)

**Comment by filipeom** [comment]
> It allows named arguments, so you don't have to worry about the order anymore, which is nice when you have a lot of them! :)

Ah yes, this is so cool! Thanks!! I'm using this everywhere moving forward :sweat_smile:

**Pull request merged**
