### PR TITLE
Fix Symbolic.concretize

### PR DESCRIPTION
**Pull request by krtab**
Fixes: https://github.com/OCamlPro/owi/issues/168
Fixes: https://github.com/OCamlPro/owi/issues/169

@filipeom This changes the output of some of the C tests so I'm requiring your review as well

### CODE REVIEW

**Comment by filipeom** [comment]
Wow, this looks great! And much more concise. However, in concretizing, we still need to pattern match on the `Ptr` value. Otherwise, `select_i32` will start discharging concrete queries to the solver like: `fix_symbol: (i32.eq choice_i32_271 (Ptr (i32 8389712) (i32 20)))`. And, we lose the chunks' bounds information in the function `check_within_bounds` just below, making it unable to identify memory bugs (the C tests that changed).

So, making `concretize` something like:

```ocaml
    let concretize (a : Expr.t) : int32 Choice_monad.t =
      let open Choice in
      match a.node.e with
      | Ptr (base, offset) ->
        let+ offset = select_i32 offset in
        Expr.(Ptr (base, Value.const_i32 offset) @: Ty_bitv S32)
      | _ ->
        let+ v = select_i32 a in
        Value.const_i32 v
```

Should be enough to solve both issues :grinning:

**Review by filipeom — APPROVED** [review]

**Comment by zapashcanon** [comment]
@krtab, I rebased your PR as I merged a big refactoring.

Otherwise, I'm fine with merging with Filipe's review being applied if it allows to recover the finding of the bugs in the tests.

**Comment by krtab** [comment]
Should be good to do.
I had to deactivate the store.wat test that will just enumerate all possible i32.

**Comment by zapashcanon** [comment]
Thanks!

**Pull request merged**
