### PR TITLE
Make tests a bit more deterministic

### PR DESCRIPTION
**Pull request by krtab**
Fix: #124

### CODE REVIEW

**Comment by krtab** [comment]
> did they change for you ?

Yes, they failed my first `dune runtest` :sweat_smile:

**Comment by zapashcanon** [comment]
Do you think you could extend this with an option to display the model but without the value ? That is only the names of the symbols and their types ?

**Comment by krtab** [comment]
New version requires https://github.com/formalsec/encoding/pull/72 to be merged

**Comment by zapashcanon** [comment]
@krtab could you promote the tests ? The CI is failing because of this.

**Comment by krtab** [comment]
I was sure I did...

**Comment by zapashcanon** [comment]
Thanks!

**Pull request merged**
