### PR TITLE
drive c compilation with clang only

### PR DESCRIPTION
**Pull request by zapashcanon**

### CODE REVIEW

**Comment by zapashcanon** [comment]
I ran the symbolic version with `O1`, this patch and a 20 seconds timeout and got the following results:

> Nothing:     74    Reached:    566    Timeout:    567    Bad:     10

Amongst the 10 bad, 3 of them were `Other 26`:

- `sv-benchmarks/c/openbsd-6.2/if_etherip-unreach-call.i`

That seems to be an invalid file:

<details><summary>Details</summary>

```c
owi-out/if_etherip-unreach-call.c:1221:45: error: invalid input constraint 'a' in asm
 1221 |   __asm volatile("xsave %0" : "=m"(*addr) : "a"(lo), "d"(hi) : "memory");
      |                                             ^
owi-out/if_etherip-unreach-call.c:2805:20: error: invalid output constraint '=a' in asm
 2805 |                  : "=a"(n), "=m"(*p)
      |                    ^
owi-out/if_etherip-unreach-call.c:2812:20: error: invalid output constraint '=a' in asm
 2812 |                  : "=a"(n), "=m"(*p)
      |                    ^
owi-out/if_etherip-unreach-call.c:2818:20: error: invalid output constraint '=a' in asm
 2818 |                  : "=a"(n), "=m"(*(unsigned long *)p)
      |                    ^
owi-out/if_etherip-unreach-call.c:2824:35: error: invalid output constraint '=a' in asm
 2824 |   __asm volatile("xchgl %0, %1" : "=a"(n), "=m"(*p) : "0"(n), "m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2829:35: error: invalid output constraint '=a' in asm
 2829 |   __asm volatile("xchgq %0, %1" : "=a"(n), "=m"(*p) : "0"(n), "m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2833:35: error: invalid output constraint '=a' in asm
 2833 |   __asm volatile("xchgq %0, %1" : "=a"(n), "=m"(*p) : "0"(n), "m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2838:20: error: invalid output constraint '=a' in asm
 2838 |                  : "=a"(n), "=m"(*(unsigned long *)p)
      |                    ^
owi-out/if_etherip-unreach-call.c:2855:45: error: invalid input constraint 'a' in asm
 2855 |   __asm volatile(" addl %1,%0" : "+m"(*p) : "a"(v));
      |                                             ^
owi-out/if_etherip-unreach-call.c:2859:45: error: invalid input constraint 'a' in asm
 2859 |   __asm volatile(" addq %1,%0" : "+m"(*p) : "a"(v));
      |                                             ^
owi-out/if_etherip-unreach-call.c:2862:45: error: invalid input constraint 'a' in asm
 2862 |   __asm volatile(" subl %1,%0" : "+m"(*p) : "a"(v));
      |                                             ^
owi-out/if_etherip-unreach-call.c:2866:45: error: invalid input constraint 'a' in asm
 2866 |   __asm volatile(" subq %1,%0" : "+m"(*p) : "a"(v));
      |                                             ^
owi-out/if_etherip-unreach-call.c:2871:35: error: invalid output constraint '+a' in asm
 2871 |   __asm volatile(" xaddl %0,%1" : "+a"(rv), "+m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2877:35: error: invalid output constraint '+a' in asm
 2877 |   __asm volatile(" xaddq %0,%1" : "+a"(rv), "+m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2883:35: error: invalid output constraint '+a' in asm
 2883 |   __asm volatile(" xaddl %0,%1" : "+a"(rv), "+m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2889:35: error: invalid output constraint '+a' in asm
 2889 |   __asm volatile(" xaddq %0,%1" : "+a"(rv), "+m"(*p));
      |                                   ^
owi-out/if_etherip-unreach-call.c:2902:46: error: invalid input constraint 'er' in asm
 2902 |   __asm volatile(" orq %1,%0" : "=m"(*ptr) : "er"(bits));
      |                                              ^
owi-out/if_etherip-unreach-call.c:2906:47: error: invalid input constraint 'er' in asm
 2906 |   __asm volatile(" andq %1,%0" : "=m"(*ptr) : "er"(~bits));
      |                                               ^
18 errors generated.
run ['/usr/bin/clang' '-O1' '--target=wasm32' '-m32' '-ffreestanding'
     '--no-standard-libraries' '-Wno-everything' '-flto=thin'
     '-Wl,--entry=main' '-Wl,--export=main' '-Wl,--lto-O0'
     '-Wl,-z,stack-size=8388608' '-I'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/libc' '-o' 'a.out.wasm'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm'
     'owi-out/if_etherip-unreach-call.c']: exited with 1
```

</details> 

- `sv-benchmarks/c/busybox-1.22.0/printf-3.i`

This one has undefined symbols again...

<details><summary>Details</summary>

```c
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __floatsitf
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __addtf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __floatsitf
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __addtf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __multf3
wasm-ld-18: error: /home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm: undefined symbol: __trunctfdf2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
run ['/usr/bin/clang' '-O0' '--target=wasm32' '-m32' '-ffreestanding'
     '--no-standard-libraries' '-Wno-everything' '-flto=thin'
     '-Wl,--entry=main' '-Wl,--export=main' '-Wl,--lto-O0'
     '-Wl,-z,stack-size=8388608' '-I'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/libc' '-o' 'a.out.wasm'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm'
     'owi-out/printf-3.c']: exited with 1%
```

</details> 

- `sv-benchmarks/c/busybox-1.22.0/od-4.i`

This one has undefined symbols too but it looks like marking some symbols as weak should fix this, cc @krtab.

<details>

```c
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: stdin
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: setbuf
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: fread
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: stdin
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: fseek
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: ferror
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: stdin
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: ferror
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: fgetc
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: fread
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: ferror
wasm-ld-18: error: /tmp/od-4-02ca46.o: undefined symbol: stdin
clang: error: linker command failed with exit code 1 (use -v to see invocation)
run ['/usr/bin/clang' '-O0' '--target=wasm32' '-m32' '-ffreestanding'
     '--no-standard-libraries' '-Wno-everything' '-flto=thin'
     '-Wl,--entry=main' '-Wl,--export=main' '-Wl,--lto-O0'
     '-Wl,-z,stack-size=8388608' '-I'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/libc' '-o' 'a.out.wasm'
     '/home/zapashcanon/.config/opam/5.1.0/share/owi/binc/libc.wasm'
     'owi-out/od-4.c']: exited with 1
```
     
</details>

Then comes the `Killed` ones.

- `sv-benchmarks/c/seq-mthreaded/pals_STARTPALS_ActiveStandby.5.ufo.BOUNDED-10.pals.c`: I'm getting a typecheck error with `-O1` (and it's running normally with `-O0`), which seems really weird to me;
- `sv-benchmarks/c/seq-mthreaded/pals_lcr-var-start-time.4.2.ufo.UNBOUNDED.pals.c` same as above
- `sv-benchmarks/c/seq-mthreaded/pals_lcr.3.1.ufo.UNBOUNDED.pals.c` same as above
- `sv-benchmarks/c/seq-mthreaded/pals_floodmax.3.1.ufo.BOUNDED-6.pals.c` same as above
- `sv-benchmarks/c/seq-mthreaded/pals_floodmax.3.4.ufo.BOUNDED-6.pals.c` same as above
- `sv-benchmarks/c/hardware-verification-bv/btor2c-lazyMod.twocount2c.c` I can not reproduce on my machine
- `sv-benchmarks/c/recursive/Ackermann02.c` I can not reproduce on my machine

In the meantime, I added a commit which tries to use a precise type when calling the main function from the crafted `start` function. It may be what fixed the last two files.

**Comment by zapashcanon** [comment]
I also checked the `Nothing` ones, to see if we were not skipping the main function. Most of them seems to be cases where the memory model can not handle some stuff, which is expected. A few of them are suspicious, I opened #270 and #271.

**Comment by zapashcanon** [comment]
So we can say it fixes #257. @krtab I'll let you merge if that looks good to you.

**Comment by krtab** [comment]
> This one has undefined symbols too but it looks like marking some symbols as weak should fix this, cc @krtab.

I don't think so. I think we are currently missing all the listed symbol in our lib C stdio.h, this should likely be made into a different issue and does not prevent this merge though

**Comment by krtab** [comment]
Inline asm and the missing stdio functions mentioned in #272 are the only bug remaining from those you mentioned if I'm correct. Merging

**Pull request merged**
